### PR TITLE
ADD Interpolate bad Channels

### PR DESCRIPTION
**Pull request by vferat**
This PR add the ability to use `.interpolate_bads` on raw, epoch and evoked data

### CODE REVIEW

**Comment by cbrnr** [comment]
Thanks, I'll take a look. Just to make life easier in the future, could you please create PRs from branches other than master?

**Comment by vferat** [comment]
No problem, sorry for the mess, I was not aware about issue due to PRs from master. I didn't change anything more than adding ` .interpolate_bads`. Thanks for the advice

**Comment by cbrnr** [comment]
No big deal, it just requires me to type 2 lines instead of 1 when checking out your branch 😄. I'll push a few more changes and this will be ready to go.

**Comment by cbrnr** [comment]
I'm catching a ValueError if some channels do not have location information. This works, but it has the same visual glitch as described in #53. So if anyone knows how to fix this this would be absolutely great!

**Comment by cbrnr** [comment]
I'm catching a ValueError if some channels do not have location information. This works, but it has the same visual glitch as described in #53. So if anyone knows how to fix this this would be absolutely great!

**Comment by cbrnr** [comment]
Thanks @vferat!

**Pull request merged**
