### PR TITLE
Add ability to drop bad epochs

### PR DESCRIPTION
**Pull request by hofaflo**
This provides an interface for [mne.Epochs.drop_bad](https://mne.tools/stable/generated/mne.Epochs.html#mne.Epochs.drop_bad).

Example dialog:
image

Only available channel types are displayed, alternatively we could always show all but grey-out non-available ones?

### CODE REVIEW

**Comment by cbrnr** [comment]
I think it would be important to indicate the units of the thresholds people are supposed to enter. Maybe this can be shown after the type in parentheses, e.g. "EEG (V)"? The units should be available somewhere in the constants module in MNE.

And yes, I think it's fine if only available types are shown.

**Comment by hofaflo** [comment]
Good idea! E.g. "stim" channels don't have a unit, is "AU" fine for that or do you prefer something else?

image

**Comment by cbrnr** [comment]
This looks great! For no unit channels I'd write nothing, so just `STIM`.

**Comment by cbrnr** [comment]
Thanks @hofaflo!

**Pull request merged**
