### PR TITLE
Added support for .mat and .npy files.

### PR DESCRIPTION
**Pull request by jgcaffari1**
addresses [this enhancement](https://github.com/cbrnr/mnelab/issues/195).

### CODE REVIEW

**Comment by cbrnr** [comment]
Alright, sorry for taking so long to review this. Would you mind implementing support for only NPY files in this PR? I think MAT files require more infos to be specified by the user because they contain several variables, whereas NPY files contain exactly one array. Therefore, I'd tackle MAT import in a separate PR.

Regarding NPY import, I think there should only be two options that users need to set before importing:

1. Sampling frequency
2. Transpose (a checkbox)

Re 1, I usually use a double spinbox widget. I would restrict the values to be greater than 0 instead of 100Hz. I wouldn't impose any other (upper) limit either. Re 2, here it would be necessary to peak into the file to determine the shape of the saved array. The shapes should be displayed in the dialog, and users should be able to transpose the data before importing with a checkbox (by default it should be unchecked).

If you don't have time, we could even add the transpose option at a later time. Then, this PR could be simplified a lot, because the dialog would contain just the sampling frequency. I'd also remove channel type and normalization, because these operations can be done later after the file has been imported.

**Comment by cbrnr** [comment]
Continued at #213.

**Comment by jgcaffari1** [comment]
I am still working on this, I had something come up at work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cbrnr** [comment]
I already made the changes, please comment in #213.

**Pull request closed without merging**
