### PR TITLE
Allow importing events from FIF files

### PR DESCRIPTION
**Pull request by hofaflo**
To facilitate reproducing [this tutorial](https://mne.tools/stable/auto_tutorials/evoked/30_eeg_erp.html)

### CODE REVIEW

**Comment by cbrnr** [comment]
Could we use just `*.fif` for the extension? The `-eve` part is a convention that not everyone uses. If the file doesn't contain any events, there should be an error anyway (but of course we should try).

**Comment by hofaflo** [comment]
Seems to work, FIF files without events give an error (from mne).

**Comment by cbrnr** [comment]
This needs another rebase.

**Comment by cbrnr** [comment]
Can you add a changelog entry please?

**Comment by hofaflo** [comment]
done!

**Comment by cbrnr** [comment]
Thanks @hofaflo!

**Pull request merged**
