### PR TITLE
FIX: error loading logo icon

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR refactors the part of the code responsible for loading the logo icon.

The path was hardcoded `mnelab/icons/mnelab-logo-macos.svg` which is not correct if the app is started out of the source directory.

@cbrnr I went with the workaround used in https://github.com/mne-tools/mne-python/pull/10456 (fallback `default` theme) but we could also consider using `importlib.resources` which does not depend on Qt. 

Closes https://github.com/cbrnr/mnelab/issues/338

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Does it work for you @cbrnr ?

**Comment by cbrnr** [comment]
Thanks @GuillaumeFavelier! Unfortunately, this doesn't seem to work, but I have some questions: 

1. How should I test this? The toolbar icons are only gone when I run MNELAB from the installed PyPI wheel. Everything works in my dev setup (which uses `pip install -e .`).
2. Using my dev setup, in your PR I don't see the app icon, whereas I do see it in `main`. I do not get the warning message at all (the warning only appears when using the 0.8.0 version from PyPI).
3. Re hard-coding the path: this is a relative path, so I thought it should work? However, it should be relative to the install location and not the CWD.
4. Why did the toolbar icons disappear in 0.8.0? They used to work in 0.7.0, and I think I didn't change anything related to icons. The only thing I did was add an app icon.

**Comment by GuillaumeFavelier** [comment]
> Unfortunately, this doesn't seem to work

Okay then I'll get back to you when I switch to my KDE desktop, my current one just removes the app icon by default.

Hopefully, I'll be able to answer some of your question too :+1:

**Comment by GuillaumeFavelier** [comment]
To have a proper testing environment, I switched to KDE (where I actually see the icon):

On `main` (ae20ca685c052e1ba9552ffc9bb6ec1d5505e6c8), from my home directory:

image

On `main`, from the `mnelab` source directory:

image

On `mnt/logo` (fc30bad0095b5a443d523a4b9db6003231017655), from my home directory:

image

**Comment by cbrnr** [comment]
Alright, so this does fix the app icon. I will try to replicate your testing env. However, I'm a bit worried about the toolbar icons, which are missing when you install from PyPI. Can you try `pip install mnelab` and see if you get icons or not? I think it works with `mnelab==0.7.0`, but icons are missing in the latest 0.8.0.

**Comment by GuillaumeFavelier** [comment]
> I'm a bit worried about the toolbar icons

My bad, I'm trying to catch up here.  As of now, I can only reproduce the issue with the app icon. I dot not have any issue with toolbar icons as of now on `main`. But I use the editable mode.

> icons are missing in the latest 0.8.0.

maybe a different issue? 

> Can you try pip install mnelab and see if you get icons or not?

Sure! Just give a few minutes to create a fresh conda env to test :+1:

**Comment by GuillaumeFavelier** [comment]
Indeed I can reproduce with `pip install`. No app or toolbar icon.

From my home directory:

image

Full log on `python 3.9`:

<details>

```
~ via 🅒 mnelab-test 
❯ pip install mnelab                    
Collecting mnelab
  Using cached mnelab-0.8.0-py3-none-any.whl (64 kB)
Collecting pyxdf>=1.16.0
  Using cached pyxdf-1.16.3-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: scipy>=1.0.0 in ./.local/lib/python3.9/site-packages (from mnelab) (1.6.3)
Collecting numpy>=1.14.0
  Using cached numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting matplotlib>=3.5.0
  Using cached matplotlib-3.5.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
Collecting PySide6>=6.2.0
  Using cached PySide6-6.2.4-6.2.4-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (268.2 MB)
Collecting mne>=0.24.0
  Using cached mne-1.0.0-py3-none-any.whl (7.5 MB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-9.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.31.2-py3-none-any.whl (899 kB)
Collecting tqdm
  Using cached tqdm-4.63.1-py2.py3-none-any.whl (76 kB)
Collecting pooch>=1.5
  Using cached pooch-1.6.0-py3-none-any.whl (56 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jinja2
  Using cached Jinja2-3.1.1-py3-none-any.whl (132 kB)
Collecting requests>=2.19.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting appdirs>=1.3.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting shiboken6==6.2.4
  Using cached shiboken6-6.2.4-6.2.4-cp36.cp37.cp38.cp39.cp310-abi3-manylinux1_x86_64.whl (1.0 MB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./source/anaconda3/envs/mnelab-test/lib/python3.9/site-packages (from requests>=2.19.0->pooch>=1.5->mne>=0.24.0->mnelab) (2021.10.8)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: urllib3, six, pyparsing, idna, charset-normalizer, requests, python-dateutil, pillow, packaging, numpy, MarkupSafe, kiwisolver, fonttools, cycler, appdirs, tqdm, shiboken6, pooch, matplotlib, jinja2, decorator, pyxdf, PySide6, mne, mnelab
Successfully installed MarkupSafe-2.1.1 PySide6-6.2.4 appdirs-1.4.4 charset-normalizer-2.0.12 cycler-0.11.0 decorator-5.1.1 fonttools-4.31.2 idna-3.3 jinja2-3.1.1 kiwisolver-1.4.1 matplotlib-3.5.1 mne-1.0.0 mnelab-0.8.0 numpy-1.22.3 packaging-21.3 pillow-9.0.1 pooch-1.6.0 pyparsing-3.0.7 python-dateutil-2.8.2 pyxdf-1.16.3 requests-2.27.1 shiboken6-6.2.4 six-1.16.0 tqdm-4.63.1 urllib3-1.26.9
```

</details>

**Comment by GuillaumeFavelier** [comment]
Could it be an issue with the wheels published on PyPI? 

Because when I build 0.8 locally, the only issue I have is with the app icon, the tool bar icons are fine.

<details>

From `mnelab` source:

```
git checkout v0.8.0
pip wheel -w ~/.wheelhouse .
```

From home directory:

```
pip install .wheelhouse/mnelab-0.8.0-py3-none-any.whl
```

image

</details>

**Comment by GuillaumeFavelier** [comment]
By the way if you prefer a more interactive collaboration, we can also talk on `Discord` @cbrnr

**Comment by GuillaumeFavelier** [comment]
@cbrnr per our offline discussion, I updated the paths to load the app icon and now use `pathlib`.

I checked locally on my linux and everything works as expected :+1:

**Comment by cbrnr** [comment]
Great! Do you want to add a changelog entry? I think this should go in "Fixes".

**Comment by GuillaumeFavelier** [comment]
I tried d3dbf5077d14db799d69b4b2a7e42b3e49251041, feel free to adapt:

> - Fix loading of application logo by ([#339](https://github.com/cbrnr/mnelab/pull/339) by [Guillaume Favelier](https://github.com/GuillaumeFavelier))

**Comment by GuillaumeFavelier** [comment]
Sorry for the typo, I'm terrible at changelog.

**Comment by cbrnr** [comment]
Thanks @GuillaumeFavelier!

**Pull request merged**
