### PR TITLE
Use platform-specific monospace fonts

### LINKED ISSUE #254: Missing font warning in History dialog
When opening _View_ – _History..._, the following warning pops up in the terminal:

```
qt.qpa.fonts: Populating font family aliases took 520 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
```

I think it would be good to fix this because half a second is noticeable.

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #254.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
On editable mode on this branch, I tried an [example](https://mnelab.readthedocs.io/en/latest/examples/erp.html) and this is what I obtain:

image

After cropping:

image

And the log on the terminal:

```
Opening raw data file /home/guillaume/mne_data/MNE-sample-data/MEG/sample/sample_audvis_filt-0-40_raw.fif...
    Read a total of 4 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
        Average EEG reference (1 x 60)  idle
    Range : 6450 ... 48149 =     42.956 ...   320.665 secs
Ready.
Reading 0 ... 41699  =      0.000 ...   277.709 secs...
```

I think it's all good in here.

*Do not mind the borderless window, I use a tiling window manager*

**Comment by GuillaumeFavelier** [comment]
Do not hesitate to tell me if you want me to test something specific @cbrnr

**Comment by GuillaumeFavelier** [comment]
Alright, I opened a dataset then clicked on "View" > "History":

image


Once again, everything looks to me @cbrnr

**Comment by cbrnr** [comment]
Nice, thanks!

**Comment by cbrnr** [comment]
Sorry to ask you again @GuillaumeFavelier, but can you confirm that with this PR you are not seeing the font warning message in the terminal?

**Comment by GuillaumeFavelier** [comment]
On the branch `fix-monospace-history` (76450c3845a6bbb2a3476875935910e21cfae7cc), I do not see any font warning message:

image

But I think this bug is really related to `macOS` because I never reproduced this on my linux.

**Pull request merged**
