### PR TITLE
Handle files that don't exist in Recent menu

### LINKED ISSUE #36: Crashes when trying to open non-existent file
I tried to open a file via `Open -> Recent`; however that file had recently been moved to a different directory, so didn't exist in its original location anymore. MNELAB just crashes in this case, where it should handle the `FileNotFoundError` exception:

```(mnelab) [hoechenberger:~]$ mnelab
QWidget::insertAction: Attempt to insert null action
Extracting parameters from /Users/hoechenberger/Google Drive/TaLa/EEG_Analysis_outdated/1_DataEEG/Sub_902_211117/TaLa_902_01.vhdr...
Traceback (most recent call last):
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mnelab/mainwindow.py", line 652, in _load_recent
    self.open_raw(fname=action.text())
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mnelab/mainwindow.py", line 322, in open_raw
    self.model.load(fname)
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mnelab/model.py", line 38, in wrapper
    f(*args, **kwargs)
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mnelab/model.py", line 119, in load
    raw = self._load_brainvision(fname)
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mnelab/model.py", line 141, in _load_brainvision
    raw = mne.io.read_raw_brainvision(fname, preload=True)
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mne/io/brainvision/brainvision.py", line 833, in read_raw_brainvision
    stim_channel=stim_channel, verbose=verbose)
  File "</Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mne/externals/decorator.py:decorator-gen-146>", line 2, in __init__
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mne/utils/_logging.py", line 89, in wrapper
    return function(*args, **kwargs)
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mne/io/brainvision/brainvision.py", line 82, in __init__
    orig_units) = _get_vhdr_info(vhdr_fname, eog, misc, scale, montage)
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mne/io/brainvision/brainvision.py", line 449, in _get_vhdr_info
    settings, cfg, cinfostr, info = _aux_vhdr_info(vhdr_fname)
  File "/Users/hoechenberger/miniconda3/envs/mnelab/lib/python3.7/site-packages/mne/io/brainvision/brainvision.py", line 348, in _aux_vhdr_info
    with open(vhdr_fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hoechenberger/Google Drive/TaLa/EEG_Analysis_outdated/1_DataEEG/Sub_902_211117/TaLa_902_01.vhdr'
[1]    3235 abort      mnelab
```

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #36. @hoechenberger can you test if this fixes the issue for you?

### CODE REVIEW

**Comment by vferat** [comment]
@cbrnr Don't know if I have to change the changelog file by myself or not ?
Perhaps some guidelines should be written in order to know how to contribute (error handling, code conventions, changelog, ect) in order to have homogenous code & interface

**Comment by cbrnr** [comment]
@vferat the author of a PR should also modify the changelog (you have to make the PR first before you know the PR number to include in the file). Yes, a guide for contributors would be helpful (I'll open a new issue).

**Comment by cbrnr** [comment]
Since it works for me, I'm going to merge. Please feel free to double-check if this solved your problem and if not open another issue.

**Comment by hoechenberger** [comment]
> Fixes #36. @hoechenberger can you test if this fixes the issue for you?

Yes it does. Thank you!

**Pull request merged**
